title: EARS
description: EARS Github Page
# The below theme statement is for the original just-the-docs theme, we are using our own fork, which is used with the remote_theme option.
#theme: just-the-docs
remote_theme: SurreyEARS/just-the-docs

markdown: kramdown

url: https://surreyears.github.io/

logo: "media/EARS_github_logo.png"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

color_scheme: ears

aux_links: false


callouts:
  note:
    color: purple
 
  info:
    color: green
 
footer_content: "© Surrey EARS"

plugins:
 - jekyll-remote-theme
